#!/bin/bash

xidfile="/run/user/"$(id -u)"/zathura-tabbed.xid"
wmclass="zathura-tabbed"

# check if a tabbed window is open
set -o pipefail
if [ -r "$xidfile" ] && xid=$(cat "$xidfile") && xprop -id "$xid" WM_CLASS 2> /dev/null | grep -q "$wmclass";
then
    wmctrl -i -R "$xid"
else
    read xid < <(tabbed -cdn "$wmclass" -p -1 2> /dev/null)
    wmctrl -i -r "$xid" -b add,maximized_vert,maximized_horz
    echo "$xid" > "$xidfile"
fi
zathura -e "$xid" "$@" &> /dev/null &
